In [33]:
import numpy as np

c = np.random.uniform(low=[1,2,1],high=[5,3,6],size=3)
d = np.random.uniform(low=[1,2,1],high=[5,3,6],size=3)


f= np.multiply(c,d)

print(c)
print(c*d)
print(f)
print(np.clip(f,a_min=[5,1,1], a_max=[9,3,2]))

[1.95239555 2.85089516 4.62839933]
[ 3.63321875  6.06714199 12.00363198]
[ 3.63321875  6.06714199 12.00363198]
[5. 3. 2.]


In [55]:
ll=list([1,2,3])
ll[0%3]


1